DROP TABLE APP_MESSENGER;
DROP TABLE APP_CONTACTS;
DROP TABLE APP_USER;
DROP TABLE APP_PICTURES;

CREATE TABLE APP_PICTURES (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	UPLOADED_AT INTEGER DEFAULT (cast(strftime('%s','now') as int)),
	NAME VARCHAR(255),
	UPLOADED_BY VARCHAR(255)
);

CREATE TABLE APP_USER (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	CREATED_AT INTEGER DEFAULT (cast(strftime('%s','now') as int)),
	LAST_ACTION INTEGER DEFAULT (cast(strftime('%s','now') as int)),
	FIRSTNAME VARCHAR(255),
	USERNAME VARCHAR(255),
	GENDER INTEGER,
	GENDER_WANTED INTEGER,
	COUNTRY VARCHAR(255),
	AGE INTEGER,
	AGE_FROM INTEGER,
	AGE_TO INTEGER,
	PICTURE VARCHAR(255),
	LANG VARCHAR(255),
	PREMIUM BOOL,
	ADULT BOOL,
	PASSWORD VARCHAR(255),
	LATEST_TOKEN VARCHAR(255)
);

CREATE TABLE APP_CONTACTS (
	INITIATOR INTEGER,
	FRIEND INTEGER,
	IS_FRIENDLY BOOL DEFAULT 1,
	FRIEND_LEVEL INTEGER DEFAULT 0,
	TURN INTEGER DEFAULT 1,
	PROGRESS INTEGER DEFAULT 0,
	PRIMARY KEY (INITIATOR, FRIEND),
	FOREIGN KEY(INITIATOR) REFERENCES APP_USER(ID),
	FOREIGN KEY(FRIEND) REFERENCES APP_USER(ID)
);

CREATE TABLE APP_MESSENGER (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	SENDER INTEGER,
	RECEIVER INTEGER,
	CONTENT VARCHAR(255),
	TYPE VARCHAR(10),
	SENDER_ANSWER_TEXT VARCHAR(255),
	RECEIVER_ANSWER_TEXT VARCHAR(255),
	CREATED_AT INTEGER DEFAULT (cast(strftime('%s','now') as int)),
	FOREIGN KEY(SENDER) REFERENCES APP_USER(ID),
	FOREIGN KEY(RECEIVER) REFERENCES APP_USER(ID)
);